server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iot
    username: phpmyadmin
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true

api:
  prefix: /api/v1

jwt:
  expiration: 600  # 10m
  expiration-refresh-token: 604800 # 7day
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
