server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartHome?createDatabaseIfNotExist=true  # Kết nối đến MySQL cục bộ
    username: root                       # Tài khoản MySQL mặc định trong XAMPP
    password:                            # Mặc định tài khoản root không có mật khẩu trong XAMPP, nếu có mật khẩu, hãy điền vào đây

  jpa:
    hibernate:
      ddl-auto: update  # Sử dụng 'update' để tự động tạo hoặc cập nhật các bảng dựa trên các entity trong JPA
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true

api:
  prefix: /api/v1

jwt:
  expiration: 600  # 10 phút
  expiration-refresh-token: 604800 # 7 ngày
  secretKey: TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI=
